// AUTOGENERATED by @mainstay/spec-to-mocks — do not edit by hand.
// Source spec: ../../examples/walkthrough/04-api-spec.yaml

export const BASE_URL = "https://api.example.com" as const;

export interface Endpoint {
  method: string;
  path: string;
  operationId: string;
  summary: string;
}

export const ENDPOINTS = [
  {"method":"GET","path":"/v1/saved-views","operationId":"listSavedViews","summary":"List the saved views visible to the current user."},
  {"method":"POST","path":"/v1/saved-views","operationId":"createSavedView","summary":"Create a new saved view."},
  {"method":"GET","path":"/v1/saved-views/{id}","operationId":"getSavedView","summary":"Retrieve a single saved view by id."},
  {"method":"PATCH","path":"/v1/saved-views/{id}","operationId":"updateSavedView","summary":"Update a saved view's name, configuration, or visibility."},
  {"method":"DELETE","path":"/v1/saved-views/{id}","operationId":"deleteSavedView","summary":"Delete a saved view."},
  {"method":"POST","path":"/v1/saved-views/{id}/default","operationId":"setDefaultSavedView","summary":"Mark a saved view as the caller's default."},
] as const satisfies readonly Endpoint[];
