// AUTOGENERATED by @mainstay/spec-to-mocks — do not edit by hand.
// Source spec: ../../examples/walkthrough/04-api-spec.yaml

/** A named, saved combination of table filters, sort, and columns. */
export interface SavedView {
  /** Unique identifier of the saved view. */
  id: string;
  /** Display name, 1-60 characters, unique per user. */
  name: string;
  /** Whether the view is private to the owner or shared with the workspace. */
  visibility: "private" | "workspace";
  /** Whether this view is the current user's default (per-user, see DEC-007). */
  is_default: boolean;
  config: ViewConfig;
  /** Identifier of the user who owns the view. */
  owner_id: string;
  /** Creation timestamp (ISO 8601, UTC). */
  created_at: string;
  /** Last update timestamp (ISO 8601, UTC). */
  updated_at: string;
}

/** Payload to create or update a saved view. */
export interface SavedViewCreate {
  /** Display name, 1-60 characters, unique per user. */
  name: string;
  /** Optional on create; defaults to "private" (DEC-011). */
  visibility?: "private" | "workspace";
  config: ViewConfig;
}

/** The table state captured by a saved view. */
export interface ViewConfig {
  /** Active filter clauses, applied with AND. */
  filters: FilterClause[];
  sort: SortClause;
  /** Ordered list of column keys shown in the table. */
  visible_columns: string[];
}

/** A single filter applied to a table column. */
export interface FilterClause {
  /** The column key being filtered. */
  column: string;
  /** The comparison operator. */
  operator: "eq" | "neq" | "contains" | "gt" | "lt";
  /** The comparison value, serialized as a string. */
  value: string;
}

/** The sort applied to the table. */
export interface SortClause {
  /** The column key being sorted. */
  column: string;
  /** Sort direction. */
  direction: "asc" | "desc";
}

/** A page of saved views. */
export interface SavedViewList {
  /** The saved views visible to the caller. */
  items: SavedView[];
  /** Total number of visible saved views. */
  total: number;
}

/** A structured error response. */
export interface Error {
  /** Stable machine-readable error code. */
  code: "unauthorized" | "forbidden" | "not_found" | "validation_failed";
  /** Human-readable error message, safe to display. */
  message: string;
}
